name: Testing and Code Metrics
env:
  DOTNET_VERSION: '6'                 # set this to the .NET major version
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-paket-${{ hashFiles('**/paket.lock') }}
          restore-keys: |
            ${{ runner.os }}-paket-
      - name: Install dependencies
        run: |
          dotnet tool restore
          dotnet paket restore
      - name: Run code checks
        run: ./build.sh -t Check